openapi: 3.0.1
info:
  title: test api
  description: Sample API for test case for k8s
  version: "1.1.1"
paths:
  /hello:
    get:
      tags:
        - TestService
      responses:
        "200":
          description: "Resulting weird api"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddProps1"
  /hello2:
    get:
      tags:
        - TestService
      responses:
        "200":
          description: "Resulting weird api"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddProps2"
components:
  schemas:
    AddProps1:
      properties:
        extra:
          type: object
          additionalProperties:
            items:
              type: string
            type: array
          description: "used extensively in k8s api and generates weird code"
        dependencies:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AddProps2"
        groups:
          type: array
          description: "names groups this user is part of"
          items:
            type: string
        name:
          type: string
        mess$age:
          $ref: "#/components/schemas/Messages"
        $justObjects:
          type: array
          items:
            $ref: "#/components/schemas/JSONType"
    AddProps2:
      properties:
        extra:
          type: object
          additionalProperties:
            type: object
            properties:
              code:
                type: integer
              text:
                type: string
    AddProps3:
      properties:
        extra:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/TimeType"
    AddProps4:
      properties:
        extra:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/TimeType"
    JSONType:
      description: "can be anything, no properties"
    TimeType:
      type: string
      format: date-time
    Messages:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          type: integer
        text:
          type: string
